### ISSUE TITLE
会考虑出 JetBrains IDE的插件吗？

### ISSUE THREAD

**Issue by liaokaime** [wulunyi/typeof-jsonc#14]
首先向你的项目表示欢迎，它对我非常有用。我看到这个项目出了vscode的插件。你知道，JetBrains 系列的产品也有很多人在用，请问你有计划推出 JetBrains 系列的插件吗？

**Comment by wulunyi** [comment]
感谢您的使用，非常抱歉这么久才回复你，也不知道你现在是否还在使用这个工具，我也是今天才知道原来还真有好多同学在使用它，挺惊喜的也挺惭愧的。最近我打算重启该项目，也不知道你现在是否还在使用，如果你还继续使用，后续我会有更新会尽快通知您

**Comment by liaokaime** [comment]
当然我一直在使用，我已经 subscribe 了你的项目，会自动收到项目的更新通知的。这个项目很有用，将来用ts的人也会越来越多，jetbrains 系列有个json2ts插件，之前的体验是不太好用。如果这个项目能出ide的插件，肯定有很多人下载的。

**Comment by wulunyi** [comment]
哈哈整起，jetbrains 没怎么用过，得研究研究它的插件
